language: cpp
dist: bionic
os: 
 - linux
before_install:
 - sudo apt update
 - sudo apt install build-essential
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get install -y gcc-9 g++9
compiler: 
  - gcc
branches:
    only:
    - master

